services:
  ldes-healing:
    build: ./
    restart: 'no'
    labels:
      - 'logging=true'
    environment:
      NODE_ENV: development
      NO_BABEL_NODE: true
      CRON_HEALING: '*/10 * * * * *'
      AUTO_HEALING: FALSE
      DIRECT_DATABASE_ENDPOINT: http://virtuoso:8890/sparql
      LDES_STREAM_BASE: https://dev.mandatenbeheer.lblod.info/streams/ldes
      LDES_STREAM: public
    ports:
      - '8082:80'
      - '9225:9229'
    volumes:
      - ./:/app
      # ignore app/dist because this is where we map the built files to, otherwise we get an infinite loop of creating files (on mac)
      - /app/dist
      - ./dist:/build/
    networks:
      - debug
networks:
  debug:
    external: true
